# Generated by Django 3.2.8 on 2022-02-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiDev', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=5000)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
