# Generated by Django 3.2.8 on 2022-02-03 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiDev', '0002_category_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='slug',
            new_name='store_link',
        ),
    ]
