# Generated by Django 3.2.8 on 2022-02-03 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiDev', '0003_rename_slug_store_store_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=5000)),
                ('mrp', models.IntegerField()),
                ('sale_price', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apiDev.category')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiDev.store')),
            ],
        ),
    ]
