# Generated by Django 3.2.8 on 2022-02-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiDev', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mrp',
            new_name='MRP',
        ),
    ]
