# Generated by Django 3.2.8 on 2022-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiDev', '0005_rename_mrp_product_mrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_mobile_num', models.CharField(max_length=17, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=50)),
                ('customer_address', models.TextField(max_length=5000)),
            ],
        ),
    ]
