# Generated by Django 3.2.8 on 2022-02-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiDev', '0007_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
